---
title: "AirBnB Listings Modelling"
author: "Pamela Afful"
format: revealjs
editor: visual
---

## Exploratory Analysis

```{r lib_read, eval=T, echo=F}
#| message: false
#| warning: false
library(dplyr)
library(knitr)
library(plotly)
library(ggplot2)
library(ggpubr)
library(lubridate)
library(zoo)
library(tidyverse)
library(GGally)
library(modelsummary)
library(stargazer)
library(gtsummary)
library(patchwork)
library(glmnet)
library(lmridge)
library(tidyr)
library(caret)
library(dplyr)
library(interactions)
library(kableExtra)
library(patchwork) 
library(knitr)
library(broom)
library(car)
library(maps)
library(RColorBrewer)
library(tree)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ranger)
library(randomForest)
library(gbm)
library(Metrics)
library(lattice)
library(PRROC)
library(yardstick)
library(ROCR)
library(readr)
library(e1071)
```

```{r data_read, eval=T, echo=F}
#| message: false
#| warning: false
listings_data<- read_csv("listings (1).csv")

listings_data_cleaned=listings_data %>% mutate(host_since=lubridate::ymd(host_since),
                         host_response_time=factor(host_response_time,levels=c("within an hour","within a few hours","within a day", "a few days or more")),
                         host_is_superhost=factor(host_is_superhost,levels=c('TRUE','FALSE')),
                         room_type=factor(room_type,levels=unique(listings_data$room_type)),
                         instant_bookable=factor(instant_bookable,level=c('TRUE','FALSE')),
                         fully_booked_30=factor(fully_booked_30, levels=c('yes','no')),
                         host_verifications=factor(case_when(host_verifications %in% c("['phone']") ~'phone_only',
                                                      host_verifications %in% c("['email', 'phone']" ,"['email', 'phone', 'work_email']", "['phone', 'work_email']") ~'phone_email',
                                                      host_verifications %in% c("['email']") ~'email_only'
                           
                         ),levels=c('phone_only','phone_email','email_only'))
                         
                         
                         )



fixed_month_str=ymd("2026-05-01")
fixed_month=floor_date(fixed_month_str,unit='month')

listings_data_cleaned$host_since_months_int =listings_data_cleaned %>% mutate(host_since=ymd(host_since)  ) %>% 
  mutate(host_since_trunc=floor_date(host_since,unit='month')) %>% 
  
  mutate(host_since_months_int= interval(host_since_trunc,fixed_month) %/% months(1) ) %>% 
  
  mutate(current_date= floor_date( today(),unit='month' ) ) %>% 
  
  dplyr::select(host_since_trunc,host_since_months_int,current_date ) %>%
  
  pull(host_since_months_int)

 # create intervals for EDA purposes
a=listings_data_cleaned %>% mutate(host_since_intervals=  cut(host_since_months_int, breaks=c(0,48,96,114,197),labels = c("0-2 yrs", "2-4 yrs", "4-6 yrs",'6+ yrs') )) %>% 
  group_by(host_since_intervals,fully_booked_30) %>% 
  summarize(n_cnt=length(host_id)) %>% 
ggplot(aes(x=fully_booked_30,y=n_cnt, fill=host_since_intervals))+
  geom_col(position="dodge")+
  labs(title = "Fully Booked vs Non Fully Booked Host Age",y='#observations',
       x = "30-day booked status",fill='host age bin')+
  theme_minimal()

a= listings_data_cleaned %>% ggplot(aes(x=price,fill=fully_booked_30)) +
  geom_boxplot()+
    labs(title = "Host Age By 30d Fully Booked Status",x='host age (months)',
       x = "30-day booked status",fill='30 booked status')+
  theme_minimal()
```

```{r target_dist, eval=TRUE, echo=F}
#| message: false
#| warning: false
#| fig-height: 6
#| fig-subcap: Spatial Plot of BNB Listings,Fully Booked 30 Label Distribution
#| fig-width: 8
#| layout-ncol: 2


# Plot the Air BNB locations


cols <- ifelse(listings_data_cleaned$fully_booked_30 == 'no', "red", "blue")


plot(listings_data_cleaned$longitude,
      listings_data_cleaned$latitude,
     xlab = "Longitude",
     ylab = "Latitude",
       pch = 16,
       cex = 0.5,
       col = cols)

legend("topright",
       legend = c("Fully Booked", "Not Fully Booked"),
       col = c("blue", "red"),
       pch = 16,
       bty = "n",
       title = "Fully Booked 30",
       cex = 0.9)



listings_data_cleaned %>% 
  count(fully_booked_30) %>% 
  mutate(
    percentage = n / sum(n),
    label = paste0(round(percentage * 100, 1), "%")
  ) %>%
  ggplot(aes(x = fully_booked_30, y = n)) +
  geom_col(fill = 'steelblue') +
  geom_text(aes(label = label), 
            vjust = -0.5, size = 3) +
  labs(
    title = "Fully Booked vs Non Fully Booked",
    y = '#observations',
    x = "30-day booked status"
  ) +
  theme_minimal()
```

```{r eda_plots, eval=TRUE, echo=FALSE}
#| message: false
#| warning: false
#| fig-height: 8.8
#| fig-width: 15
num_vars=listings_data_cleaned %>% group_by(fully_booked_30) %>% summarize(
  avg_host_response_rate=mean(host_response_rate),
  avg_host_acceptance_rate=mean(host_acceptance_rate),
  avg_host_listings_count=mean(host_listings_count),
  avg_price=mean(price),
  avg_minimum_nights=mean(minimum_nights),
  avg_review_scores_rating=mean(review_scores_rating)
)

host_age_dist=listings_data_cleaned %>% ggplot(aes(x=host_since_months_int,fill=fully_booked_30))+
  geom_boxplot()+
  labs(title='Host Age Distribution by 30d Fully Booked Status',x='Host Age (months)',fill='Status')+theme_minimal()
  


vars <- c(
  "host_response_rate",
  "host_acceptance_rate",
  "host_listings_count",
  "price",
  "minimum_nights",
  "review_scores_rating"
)



# Initialize empty list
plot_list <- list()

# Loop through variables
for (var in vars) {
  
  # Create summary dataframe dynamically
  df_plot <- listings_data_cleaned %>%
    group_by(fully_booked_30) %>%
    summarise(mean_value = mean(.data[[var]], na.rm = TRUE))
  
  # Create plot
  p <- ggplot(df_plot, aes(x = fully_booked_30, y = mean_value)) +
    geom_col(fill = "steelblue") +
    labs(
      title = paste("Average", gsub("_", " ", var), "by Booking Status"),
      x = "30-day booked status",
      y = paste("Average", gsub("_", " ", var))
    ) +
    theme_minimal()
  
  # Store in list
  plot_list[[var]] <- p
}

# View one example

vars <- c(
  "host_response_rate",
  "host_acceptance_rate",
  "host_listings_count",
  "price",
  "minimum_nights",
  "review_scores_rating"
)

(plot_list[["price"]]+plot_list[["minimum_nights"]]+plot_list[["review_scores_rating"]])/ (plot_list[["host_acceptance_rate"]]+plot_list[["host_response_rate"]]+plot_list[["host_listings_count"]])+host_age_dist
```

```{r,cleaned_data, echo=F,eval=T}
features_all=names(listings_data_cleaned)
features=features_all[! features_all %in% c('host_since','host_id', 'fully_booked_30_lab')]

listings_data_cleaned_features=listings_data_cleaned %>% dplyr::select(any_of(features))

head(listings_data_cleaned_features)

```

```{r svm_fit, eval=T, echo=F}
#| message: false
#| warning: false

library(doParallel)
library(foreach)

# Use grid search to fid the optimal Cost Parameter C

# n_cores <- parallel::detectCores() - 1  # leave one core free
# cl <- makeCluster(n_cores)
# clusterEvalQ(cl, library(e1071))
# registerDoParallel(cl)
# 
# tune.control()
# svm_model <- tune.svm( fully_booked_30~., data=
# listings_data_cleaned_features,kernel='linear',
# cost=seq(0.15, 3, by = 0.15),type='C-classification',
# tunecontrol = tune.control(cross = 10) # k=10 cross validation
# )
# stopCluster(cl)
# registerDoSEQ()
# save model 

#saveRDS(svm_model, "svm_model.rds")
liner_svm_model=readRDS("svm_model.rds")
liner_svm_model$best.model


```

```{r}

#| message: false
#| warning: false

library(doParallel)
library(foreach)

# Use grid search to fid the optimal Cost Parameter C

# n_cores <- parallel::detectCores() - 1  # leave one core free
# cl <- makeCluster(n_cores)
# clusterEvalQ(cl, library(e1071))
# registerDoParallel(cl)
# 
# tune.control()
# nl_svm_model <- tune.svm( fully_booked_30~., data=
# listings_data_cleaned_features,kernel='radial',
# cost=seq(0.15, 3, by = 0.15),
# gamma = c(seq(0.05,1,0.20),1),
# type='C-classification',
# tunecontrol = tune.control(cross = 10) # k=10 cross validation
# )
# stopCluster(cl)
# registerDoSEQ()
# save model

#saveRDS(nl_svm_model, "nl_svm_model.rds")
nl_svm_model=readRDS("nl_svm_model.rds")
nl_svm_model$best.model

```

```{r}
kable(data.frame(
  best_cost = nl_svm_model$best.parameters$cost,
  best_gamma = nl_svm_model$best.parameters$gamma,
  best_cross_validation_error = nl_svm_model$best.performance
))


# 
```

```{r nn_fit, eval=T, echo=F}
#| message: false
#| warning: false




Sys.setenv(JAVA_HOME="C:/Program Files/Java/jdk-26.0.1")

library(h2o)
library(caret)
local_h2o <- h2o.init()

options("h2o.use.data.table" = FALSE)

```

```{r,scale_train_test_split, echo=F, eval=T}

# scale features

x=data.matrix(subset(listings_data_cleaned_features, select=-fully_booked_30));
train_scaled=data.frame(scale(x, center = TRUE, scale = TRUE))


train_scaled$fully_booked_30=listings_data_cleaned_features$fully_booked_30

names(subset(train_scaled,select=-fully_booked_30))


listings_h2o_train <- as.h2o(train_scaled)

```

Apply regularization to hedge against over fitting

```{r,nn_gridsearch,eval=T,echo=F}
hidden_options <- list(c(5), c(10), c(15), c(15,10,5))
l1_options <- c(0.05,0.15,0.25) #l1 options
epochs_options <- c(500, 1000, 1500,2000)

feature_names=names(subset(train_scaled,select=-fully_booked_30))
target=names(subset(train_scaled,select=fully_booked_30))



n_cores <- parallel::detectCores() - 1  # leave one core free
cl <- makeCluster(n_cores)
clusterEvalQ(cl, library(h2o))
registerDoParallel(cl)
# 
listings_grid <- h2o.grid(
  algorithm = "deeplearning",
  grid_id = "listings_nn_grid",
  hyper_params = list(
    hidden = hidden_options,
    l1 = l1_options,
    epochs = epochs_options
  ),
  x = feature_names,
  y = target,
  training_frame = listings_h2o_train,
  activation = "Tanh",
  seed = 1,
  reproducible = TRUE,
  balance_classes=T, # again for imabalnced data
  fold_assignment = "Stratified", # for balanced validation/train sets since data is imbalanced
  nfolds = 10
)

h2o.saveGrid(grid_directory = "C:/Users/Admin/OneDrive/Desktop/UCT_Masters_Coursework/Supervised Learning/SL_Assignment_3", 
 
             grid_id = "listings_nn_grid")

stopCluster(cl)
registerDoSEQ()

#saveRDS(listings_grid, "nn_listings_grid.rds")
#nn_model=readRDS("nn_listings_grid.rds")


nn_model=h2o.loadGrid(grid_path="listings_nn_grid")

grid_results=h2o.getGrid(
  grid_id = "listings_nn_grid",
  sort_by = "logloss", # USE as choosing metrics
  decreasing = FALSE # We want the smallest logloss at the top
)




```

```{r,nn_best,eval=TRUE,echo=F}

library(ggplot2)
library(plotly)
best_model=grid_results@model_ids[[1]]



# Get model results
grid_metrics=data.frame(grid_results@summary_table)
fig=grid_metrics %>% mutate(l1=factor(l1, levels= sort(unique(grid_metrics$l1))),
                            hidden=factor(hidden, levels= c('5','10','15',"[15, 10, 5]") )
                            ) %>% 
  group_by(hidden,l1) %>% 
  summarize(cv_logloss=mean(logloss)) %>% 
  ggplot(aes(x=l1,y=cv_logloss)) +
  #geom_line()+
  geom_bar(fill='steelblue',stat = "identity", position = "dodge")+
  
  facet_wrap(.~hidden,scales='free_y',labeller =label_both)+
  #coord_cartesian(ylim = c(0.443, 0.4577))+
  labs(title='NN Gridsearch Summary',x='epochs',y='CV Log Loss')+
  theme_minimal()
ggplotly(fig)
```

```{r, nn_best_model, echo=F, eval=TRUE}


best_model=h2o.getModel(grid_results@model_ids[[1]])

best_model_perf=h2o.performance(model = best_model)
best_model_perf
```

```{r, best_mod_par, echo=F, eval=T}

best_model=h2o.getModel(model_id = grid_results@model_ids[[1]])

report_model_parameters <- function(model, model_grid) {
  best_hyperparameters <- model_grid@summary_table[1,]
  best_model_summary <- model@model$model_summary
  out <- c(
    best_hyperparameters,
    best_model_summary
  )
  return(out)
}
```
